### ISSUE TITLE
USER STORY :Manage a poll

### ISSUE THREAD

**Issue by kreilly86** [kreilly86/love-running#6]
In order to capture the data from a user pole as an administrator, I can link to a database to store the data and perform calculations on it
  
## Acceptance Criteria
- Provide a way to link data inputted from user to external spreadsheet 
- Write code that will parse and analyse the poll data

## Tasks

- [ ] Link poll data to spreadsheet
- [ ] Write code to calculate results from poll responses
- [ ]  Write code to generate further actions based on calculations
